FROM node:20-alpine

WORKDIR /app

RUN npm install -g firebase-tools

COPY . . 
COPY .firebaserc ./
COPY firebase.json ./

RUN cd packages/functions && yarn install && yarn build

EXPOSE 5001

# CMD ["firebase", "emulators:start", "--only", "functions"]
CMD ["yarn", "start:be"]